test_that("reader source identity is SHA-256 based and path private", {
  first_dir <- tempfile("ngeo-source-a-")
  second_dir <- tempfile("ngeo-source-b-")
  dir.create(first_dir)
  dir.create(second_dir)
  on.exit(unlink(c(first_dir, second_dir), recursive = TRUE), add = TRUE)
  first <- file.path(first_dir, "image.nii")
  second <- file.path(second_dir, "image.nii")
  writeBin(as.raw(1:32), first)
  file.copy(first, second)

  first_record <- neurogeo:::.ngeo_source_record(first, "test", TRUE)
  second_record <- neurogeo:::.ngeo_source_record(second, "test", TRUE)
  expect_identical(first_record$source_id, second_record$source_id)
  expect_identical(first_record$checksum_sha256, second_record$checksum_sha256)
  expect_false(grepl(normalizePath(first_dir), first_record$source_id, fixed = TRUE))
  expect_null(first_record$path)
})

test_that("file-backed logical identity survives a cross-machine path change", {
  first_dir <- tempfile("ngeo-file-a-")
  second_dir <- tempfile("ngeo-file-b-")
  dir.create(first_dir)
  dir.create(second_dir)
  on.exit(unlink(c(first_dir, second_dir), recursive = TRUE), add = TRUE)
  first <- file.path(first_dir, "values.bin")
  second <- file.path(second_dir, "values.bin")
  writeBin(as.raw(1:32), first)
  file.copy(first, second)

  a <- neurogeo:::.ngeo_file_source_identity(first, TRUE)
  b <- neurogeo:::.ngeo_file_source_identity(second, TRUE)
  expect_identical(a$source_id, b$source_id)
  expect_identical(a$sha256, b$sha256)
  expect_false(identical(a$path, b$path))
})
